# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: myvote_engine/rpc/session.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'myvote_engine/rpc/session.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fmyvote_engine/rpc/session.proto\x12\tmyvote.v1\"\x8c\x01\n\x0bOpenSession\x12\x18\n\x10protocol_version\x18\x01 \x01(\r\x12\x12\n\nsession_id\x18\x02 \x01(\t\x12\x17\n\x0fsource_language\x18\x03 \x01(\t\x12\x17\n\x0ftarget_language\x18\x04 \x01(\t\x12\x1d\n\x15translation_budget_ms\x18\x05 \x01(\x01\"o\n\x08PcmFrame\x12\x10\n\x08track_id\x18\x01 \x01(\t\x12\x15\n\rcapture_epoch\x18\x02 \x01(\t\x12\x10\n\x08sequence\x18\x03 \x01(\x04\x12\x15\n\rstart_time_ns\x18\x04 \x01(\x04\x12\x11\n\tpcm_f32le\x18\x05 \x01(\x0c\"d\n\x08\x41udioGap\x12\x10\n\x08track_id\x18\x01 \x01(\t\x12\x0e\n\x06reason\x18\x02 \x01(\t\x12\x1f\n\x12next_start_time_ns\x18\x03 \x01(\x04H\x00\x88\x01\x01\x42\x15\n\x13_next_start_time_ns\"\x0f\n\rFinishSession\"\x0b\n\tHeartbeat\"\xe0\x01\n\rClientMessage\x12&\n\x04open\x18\x01 \x01(\x0b\x32\x16.myvote.v1.OpenSessionH\x00\x12$\n\x05\x61udio\x18\x02 \x01(\x0b\x32\x13.myvote.v1.PcmFrameH\x00\x12\"\n\x03gap\x18\x03 \x01(\x0b\x32\x13.myvote.v1.AudioGapH\x00\x12*\n\x06\x66inish\x18\x04 \x01(\x0b\x32\x18.myvote.v1.FinishSessionH\x00\x12)\n\theartbeat\x18\x05 \x01(\x0b\x32\x14.myvote.v1.HeartbeatH\x00\x42\x06\n\x04\x62ody\"\x8b\x01\n\rServerMessage\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x16\n\x0e\x65vent_sequence\x18\x02 \x01(\x04\x12\x0c\n\x04kind\x18\x03 \x01(\t\x12\x12\n\nsegment_id\x18\x04 \x01(\t\x12\x11\n\tdata_json\x18\x05 \x01(\t\x12\x19\n\x11server_elapsed_ms\x18\x06 \x01(\x01\x32X\n\rSpeechGateway\x12G\n\rStreamSession\x12\x18.myvote.v1.ClientMessage\x1a\x18.myvote.v1.ServerMessage(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'myvote_engine.rpc.session_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OPENSESSION']._serialized_start=47
  _globals['_OPENSESSION']._serialized_end=187
  _globals['_PCMFRAME']._serialized_start=189
  _globals['_PCMFRAME']._serialized_end=300
  _globals['_AUDIOGAP']._serialized_start=302
  _globals['_AUDIOGAP']._serialized_end=402
  _globals['_FINISHSESSION']._serialized_start=404
  _globals['_FINISHSESSION']._serialized_end=419
  _globals['_HEARTBEAT']._serialized_start=421
  _globals['_HEARTBEAT']._serialized_end=432
  _globals['_CLIENTMESSAGE']._serialized_start=435
  _globals['_CLIENTMESSAGE']._serialized_end=659
  _globals['_SERVERMESSAGE']._serialized_start=662
  _globals['_SERVERMESSAGE']._serialized_end=801
  _globals['_SPEECHGATEWAY']._serialized_start=803
  _globals['_SPEECHGATEWAY']._serialized_end=891
# @@protoc_insertion_point(module_scope)
