# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from myvote_engine.rpc import session_pb2 as myvote__engine_dot_rpc_dot_session__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in myvote_engine/rpc/session_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SpeechGatewayStub:
    """Normalized audio, independently streamed results. Authentication is TLS/mTLS.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamSession = channel.stream_stream(
                '/myvote.v1.SpeechGateway/StreamSession',
                request_serializer=myvote__engine_dot_rpc_dot_session__pb2.ClientMessage.SerializeToString,
                response_deserializer=myvote__engine_dot_rpc_dot_session__pb2.ServerMessage.FromString,
                _registered_method=True)


class SpeechGatewayServicer:
    """Normalized audio, independently streamed results. Authentication is TLS/mTLS.
    """

    def StreamSession(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SpeechGatewayServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamSession': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamSession,
                    request_deserializer=myvote__engine_dot_rpc_dot_session__pb2.ClientMessage.FromString,
                    response_serializer=myvote__engine_dot_rpc_dot_session__pb2.ServerMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'myvote.v1.SpeechGateway', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('myvote.v1.SpeechGateway', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SpeechGateway:
    """Normalized audio, independently streamed results. Authentication is TLS/mTLS.
    """

    @staticmethod
    def StreamSession(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/myvote.v1.SpeechGateway/StreamSession',
            myvote__engine_dot_rpc_dot_session__pb2.ClientMessage.SerializeToString,
            myvote__engine_dot_rpc_dot_session__pb2.ServerMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
